### ISSUE TITLE
Strings.MO löschen

### ISSUE THREAD

**Issue by Ni42** [ZHecker/Oxygen_Not_Included_German#22]
Können wir diese Binary-Datei löschen und evtl. ignorieren? Das Spiel nutzt die nicht, und sie stört immer nur in den Diffs.

**Comment by Xandras** [comment]
-.- erledigt und etwas chaos gemacht war en versehen das die upgedatet wurde 

Beta- passt jetzt

**Comment by Ni42** [comment]
Nö, die wird ja von Poedit aktualisiert XD 
Dachte nur wenn sie weg ist, kommt sie auch nicht in den Weg.

PS: Ich glaube du kannst die PR-Branches auch löschen, die hier noch bei Github zu sehen sind.

**Comment by Xandras** [comment]
ich nicht der ersteller ja

**Comment by Ni42** [comment]
Du bist der Ersteller ;) Nur Collaborators können Branches hier erstellen, die kommen vermutlich vom Auschecken von PRs.

**Comment by Xandras** [comment]
bin als colaborator eingeladen da siehts etwas anders aus XP
