### ISSUE TITLE
Texte leicht überlappt

### ISSUE THREAD

**Issue by xXDarkNovaXx** [ZHecker/Oxygen_Not_Included_German#28]
Die Texte überlappen sich etwas aber ansonsten kann ich noch nicht viel sagen hab erst angefangen mit dem Spiel

Screenshot:
http://prntscr.com/erln1e

**Comment by Ni42** [comment]
Ist leider so gut wie unmöglich da bessere Kategoriebezeichnungen zu finden, die den begrenzten Platz ausnutzen. Seit Klei die Schriftart geändert hat, ist das noch nerviger :/

**Comment by xXDarkNovaXx** [comment]
Ach das liegt an der Schriftart?
Vllt mal Klei anschreiben vllt findet man mit denen eine Lösung

**Comment by xXDarkNovaXx** [comment]
Ich weiß nicht ob das Problem am Entwickler hängt oder der Übersetzung 
Aber hier mal ein Screenshot
Anstatt das der Text angezeigt wird wird der so falsch angezeigt

Screenshot:
http://prntscr.com/ermgn4

**Comment by Ni42** [comment]
Ja, die Schriftart wurde mal getauscht, weil sie keine Sonderzeichen unterstützt hat, dadurch haben sich aber auch die Buchstabenabstände vergrößert, was bei dem schmalen Platz unten zu noch mehr Problemen geführt hat... 

In der Übersetzungsdatei ist der Gasfilter ganz normal formatiert, allerdings passiert das bei mir auch, dass der so gequetscht wird.

**Comment by RabaNatz** [comment]
Ich persönlich finde das nicht schlimm mit den Überlappen..

Tolle Arbeit die du da gemacht hast. Paar Sachen sind noch englisch, Aber die werden bestimmt noch angepasst oder?

**Comment by Ni42** [comment]
Ich habe nicht alles übersetzt, der Großteil stammt von @Xandras denke ich ;-)

**Comment by RabaNatz** [comment]
Ach okay. Sind mehrere die das Übersetzen.. 

Dann danke an euch :)
