### ISSUE TITLE
Steam Workshop

### ISSUE THREAD

**Issue by Ni42** [ZHecker/Oxygen_Not_Included_German#32]
Wer von uns stellt das rein und hält es aktuell mit dem Repository?

Außerdem: ist es sinnvoll, dass wir nur 1 Person mit Commitzugriff hier haben und wir auch niemanden hinzufügen können. ZHecker scheint ja AFK zu sein.

**Comment by Xandras** [comment]
Habs mal im Workshop hochgeladen mit link zu Github. Man kann Mitwirkende bei Steam hinzufügen sofern ich den Steamnamen hab. wegen Github... kp

**Comment by Ni42** [comment]
Mitwirkende können glaube nichts tun außer sich freuen, haben keine Bearbeitungsrechte... Kannst du das aktuell halten?

Sollen wir das Hauptrepo wechseln? Oder hast du Möglichkeiten, ZHecker zu kontaktieren?

**Comment by Xandras** [comment]
ich Versuchs mal über das klei Forum bin in ca. 2h zu Hause dann versuch ichs.
 Ansonsten wechseln wir das Hauptrepo. 

ich halt das auf steam Aktuell

**Comment by Ni42** [comment]
Hatte ich vor längerem schonmal gemacht, da hab ich keine Antwort bekommen :/
Über den Support von Github kann man auch den "Forkstatus" entfernen lassen, wenn wir eines von unseren beiden Repos nehmen.

**Comment by Xandras** [comment]
hmm ok dann hat sich das Thema erledigt würde ich sagen kümmerst du dich darum? ich pass dann die links in der Beschreibung auf steam an

**Comment by Ni42** [comment]
Ok, ich sag dann einfach mal, wir machen in meinem Repository weiter. Hab dich dort als Collaborator eingeladen und Issues aktiviert.
