### ISSUE TITLE
Oxygen not Included Patch 210162 Thermal Upgrade

### ISSUE THREAD

**Issue by Xandras** [ZHecker/Oxygen_Not_Included_German#9]
ich bin gad dabei die string.po datei an Kommendes Update anzupassen es ist einiges dazugekommen

**Comment by Ni42** [comment]
Oha, das ist einiges. Bin grade mal durchgegangen, es sind ein paar Änderungen weggefallen, die vorhin gemergt wurden, und sich der englische Text nicht geändert hatte. War das bewusst?

**Comment by DieMuhKuh12** [comment]
Ich schaue mir das auch mal an. Ist nicht so einfach, denn habe hier in Indonesien gerade viel zu tun.

**Comment by Ni42** [comment]
@Xandras Formatierung im neuesten commit ist etwas komisch, ziemlich viele Leerzeilen. Hattest du mal geschaut, warum nicht alle Übersetzungen aktuell sind, oder ist das schon behoben? Das Diff ist ja riesig.

Wenn die Formatierung stimmt, werde ich evtl auch etwas weiter machen. War "Beta-" mit dem Bindestrich hinten Absicht beim Branch-Name? xD

**Comment by Xandras** [comment]
@Ni42 die Leerzeichen waren in der neuen Datei drin die kommen noch raus stören aber nicht die funktion
ich schau dass ich das morgen hineinbekomme das die Beta up to date ist 

wegen beta- tjoa.... ich geb mal dem Desktop Client die schuld XP

**Comment by Ni42** [comment]
Möchte nur nicht dass die Diffs kaputt aussehen. Wenn du das bis morgen machst, kann ich auch mal anfangen, weiter zu übersetzen - sag Bescheid wenn du erstmal "durch" bist. Mag nur ungern in den PRs rumbasteln wegen Leerzeichen ^^

**Comment by Xandras** [comment]
Habs doch noch heute komplett gemacht bin leicht müde und hoffe dass ich alles erwischt hab kannst anfangen 

Es sind einiges rausgeflogen und auch einiges dazugekommen

**Comment by Ni42** [comment]
Hättest auch einfach sagen können, keine Lust, es gibt ja auch Skripte zum Reparieren. PRs kommen denke ich heute abend auf den Beta-Branch. Jetzt wo man wieder Nahrung hat, kann ich auch wieder spielen XD

**Comment by Xandras** [comment]
warum einfach wenns auch kompliziert geht?? XP
